disabled_rules:
  - closure_parameter_position
  - trailing_closure
  - opening_brace
  - trailing_comma
  - multiple_closures_with_trailing_closure
  - line_length

opt_in_rules:
  - empty_count
  - force_unwrapping
  - modifier_order
  - fatal_error_message
  - no_extension_access_modifier
  - weak_delegate
  - closure_body_length
  - closure_end_indentation
  - capture_variable

excluded:
  - Pods
  - Carthage
  - .build
  - .swiftpm
  - .spm
  - fastlane
  - vendor
  - .git

closure_body_length:
  warning: 32
file_length:
  warning: 300
  error: 800
nesting:
  type_level:
    warning: 3
    error: 5
  function_level:
    warning: 5
    error: 7
force_unwrapping:
  severity: warning
weak_delegate:
  severity: error
force_cast:
  severity: warning
force_try:
  severity: warning
fatal_error_message:
  severity: warning
large_tuple:
  warning: 5
  error: 8
type_name:
  min_length:
    warning: 3
    error: 1
  max_length:
    warning: 42
    error: 50
  excluded:
    - Db
    - Id
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - db
    - id
    - on
reporter: "xcode"
